{% set name = "mdf-connect-client" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdf_connect_client-{{ version }}.tar.gz
  sha256: 67f05a6ee8d42c466067c491ecc364d4c473c15707758ba26c55d548720af1b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - mdf_toolbox >=0.5.0
    - nameparser >=1.0.4
    - python >={{ python_min }}
    - requests >=2.18.4

test:
  imports:
    - mdf_connect_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materials-data-facility/connect_client
  summary: Materials Data Facility Connect Client
  license: SGI-B-2.0
  license_file: NOTICE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
